### ISSUE TITLE
org-save-all-org-buffers error (wrong-number-of-arguments #3)

### ISSUE THREAD

**Issue by Keisn1** [Trevoke/org-gtd.el#190] opened 2023-09-24 18:29 UTC
Hi I'm getting an error when I try to clarify Items. I can clarify one, and gtd will refile but then I get an empty clarify buffer.

1. Capture some Issues
2. Run org-gtd-process-inbox (or clarify-item)
3. C-c c to file it
4. choose action
5. choose tag
6. Hit enter

I'm running Doom Emacs
- Emacs: GNU Emacs 29.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 2.24.33, cairo version 1.16.0)
 of 2023-09-21
- Framework: Doom
- Org: Org mode version 9.7 (9.7-??-e90a8a6 @ /home/kaypro/.config/emacs/.local/straight/build-29.1/org/)

>Debugger entered--Lisp error: (wrong-number-of-arguments #<subr org-save-all-org-buffers> 3)
  org-save-all-org-buffers(nil nil ("Actions" "/home/kaypro/gtd/org-gtd-tasks.org" "^\\(\\*+\\)\\(?: +\\(CNCL\\|DONE\\|NEXT\\|TODO\\|WAIT\\)\\)?\\..." 2))
  apply(org-save-all-org-buffers (nil nil ("Actions" "/home/kaypro/gtd/org-gtd-tasks.org" "^\\(\\*+\\)\\(?: +\\(CNCL\\|DONE\\|NEXT\\|TODO\\|WAIT\\)\\)?\\..." 2)))
  org-refile(nil nil ("Actions" "/home/kaypro/gtd/org-gtd-tasks.org" "^\\(\\*+\\)\\(?: +\\(CNCL\\|DONE\\|NEXT\\|TODO\\|WAIT\\)\\)?\\..." 2))
  org-gtd-refile--do("Actions" "* Actions\n:PROPERTIES:\n:ORG_GTD: Actions\n:END:\n")
  org-gtd-single-action--apply()
  org-gtd-organize--call(org-gtd-single-action--apply)
  #<subr org-gtd-single-action>()
  apply(#<subr org-gtd-single-action> nil)
  #f(compiled-function (fn &rest args) #<bytecode 0xaa9abbe94f3620e>)(#<subr org-gtd-single-action>)
  apply(#f(compiled-function (fn &rest args) #<bytecode 0xaa9abbe94f3620e>) #<subr org-gtd-single-action> nil)
  (lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode 0x14a6b62af05c562f>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0xaa9abbe94f3620e>) fn args))(#<subr org-gtd-single-action>)
  apply((lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode 0x14a6b62af05c562f>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0xaa9abbe94f3620e>) fn args)) #<subr org-gtd-single-action> nil)
  org-gtd-single-action()
  funcall-interactively(org-gtd-single-action)
  command-execute(org-gtd-single-action)

**Comment by Trevoke** [comment] 2023-09-24 18:39
Hi! Thanks for trying this out. Based on the subject and the error, is this the same issue as https://github.com/Trevoke/org-gtd.el/issues/178 ?

**Comment by Keisn1** [comment] 2023-09-24 18:47
Yepp :D 
Also had the line in my config
`(advice-add 'org-refile :after 'org-save-all-org-buffers)`

**Comment by Trevoke** [comment] 2023-09-25 20:12
Out of curiosity, where did you find this line of code, do you know?

--

Aldric.

**Comment by Keisn1** [comment] 2023-09-28 18:20
https://systemcrafters.net/emacs-from-scratch/organize-your-life-with-org-mode/

I was about to mention that to him, as well.

**Comment by Trevoke** [comment] 2023-10-07 15:38
Replied via email - obtained from systemcrafters. 

This issue is a duplicate of #178, closing.

**Closed by Trevoke** 2023-10-07 15:38 UTC
Labels: duplicate
