### ISSUE TITLE
Attempts to clarify give me a "No refile targets" message and the buffer remains

### ISSUE THREAD

**Issue by pdxmph** [Trevoke/org-gtd.el#148] opened 2023-05-16 14:52 UTC
I'm using Doom Emacs with the basic config proposed in the docs. 

I enter org-gtd mode. 

Capturing to inbox works fine. 

Attempts to process the inbox: 

- I get to an item, clarify it, and use `C-c c` (or just invoke `org-gtd-organize` directly) and select single action, project, or whatever
- I provide a tag when prompted
- The buffer remains in place
- I see a "No refile targets" message. 

If I repeat org-gtd-organize, it just redecorates according to the type I assign it (single action, project, etc.), adding more cookies and tags (so "household" becomes ":household:household:"

Each time, I see a "No refile targets" message. 

When I look in org-gtd-tasks.org, I see a bunch of headings that were apparently created during this process:

```
* Projects
:PROPERTIES:
:TRIGGER: org-gtd-next-project-action org-gtd-update-project-task!
:ORG_GTD: Projects
:END:

* Actions
:PROPERTIES:
:ORG_GTD: Actions
:END:

* Actions
:PROPERTIES:
:ORG_GTD: Actions
:END:

* Actions
:PROPERTIES:
:ORG_GTD: Actions
:END:
```

So -- the automation is missing somewhere.

**Comment by Trevoke** [comment] 2023-05-16 15:16
Hmm, it looks like, based on the org file you shared, that you first tried to refile a project, then three times a single action.

This is surprising since, well, I have tests that do the same thing, and they work.

First question: on which version of emacs are you using doom? (C-h v emacs-version RET)

Second, a request: I wonder if you have some kind of refile cache option enabled. Could you run `C-0 C-c r` and then try again?

This might be another org-mode setting I need to override to allow this to work as intended.

**Comment by pdxmph** [comment] 2023-05-16 16:46
My `emacs-version` is 28.2. 

I tried `C-0 C-c r` in a few contexts and each time got `C-c r is undefined` (in both `org-gtd-mode` and not). 

I have some time and don't mind trying a few things, so I will bisect my org config and see if I can isolate what part of my existing org config could be a problem. If there are any other troubleshooting steps you can recommend, I don't mind trying them out.

**Comment by Trevoke** [comment] 2023-05-16 17:05
Hmm my apologies! I forgot you were using doom emacs.
Try `M-: (org-refile-cache-clear) RET` then try again.

(the way I got to this function is by looking at the help for the variable `org-refile-use-cache` and the help for the function `org-refile`).

**Comment by pdxmph** [comment] 2023-05-16 17:45
So, I went ahead and started to bisect but also noticed I had some org stuff in `custom.el` that I _thought_ I'd more or less automated with explicit configuration in `config.el`. Maybe it was just sitting in there and I never took it out. I removed that and it seemed to unstick things. 

If the problem somehow comes up again, I'll clear the cache and report back.

**Comment by Trevoke** [comment] 2023-05-16 18:09
Okay, glad to hear it! Would you mind sharing what you had found in there that could be related? It might still be something I can override in the code, to make sure it Just Works.

**Comment by pdxmph** [comment] 2023-05-16 18:49
It was just the `org-agenda-files` list in `custom.el`. I deleted the whole line, and something put it back, but things still worked. 

I just did a diff to see if I could catch anything I changed, missed, and I see that I also didn't reenable org-journal's agenda integration, and had commented out a few things meant to pull encrypted org files (`.org.gpg`) in as agenda files:

```
;(add-to-list 'org-agenda-files "~/org/journal")
;(add-to-list 'org-agenda-files "~/org/journal/*.org.gpg")
```

**Comment by Trevoke** [comment] 2023-05-16 19:12
Oh, weird. Alright, I'm going to close this issue, then, but do let me know if the problem comes back, there may always be a weird interaction with an arcane area of code that I haven't thought about trying.

**Closed by Trevoke** 2023-05-16 19:12 UTC
