### ISSUE TITLE
`org-gtd-archive-complete-projects` does not archive a project ending in a `CANCELED` todo

### ISSUE THREAD

**Issue by mobatmedia** [Trevoke/org-gtd.el#62] opened 2021-09-24 15:37 UTC
Running `(org-gtd-archive-complete-projects)` does not archive a projecty ending with a `CANCELED` todo.

**Comment by Trevoke** [comment] 2021-09-24 17:00
This is a duplicate of #1 , so I will close this issue. Thanks for reporting it!

**Closed by Trevoke** 2021-09-24 17:00 UTC
Labels: duplicate
