### ISSUE TITLE
Error: "org-gtd-agenda--prefix-format: Wrong number of arguments"

### ISSUE THREAD

**Issue by seelabs** [Trevoke/org-gtd.el#174] opened 2023-05-30 00:07 UTC
I recently installed emacs 29 pretest 2 (this one: https://alpha.gnu.org/gnu/emacs/pretest/emacs-29.0.91.tar.xz). Everything seems to work until I use org-gtd. In particular, if I run `org-gtd-engage` I get an error, and from then on I get an error on nearly every command (including yanking lines or moving from one line to the other). I'm running the latest doom emacs. I'll note that org-gtd worked well for me in the past.

A couple things I tried:
1) Recompiling and disabling native compilation. This did not solve it.
2) Downgrading to emacs 29 pretest 1, where org-gtd worked for me before. This did not solve it.

I tried to diagnose this by setting `debug-on-error`, but that does not drop me into a debugger. 

I know that I'm running a pre-release, but thought I'd report it anyway.

Here's the output from the messages buffer, if it helps:

```
Waiting for git... [2 times]
Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
Doom loaded 235 packages across 43 modules in 1.315s
[yas] Check your `yas-snippet-dirs': /home/swd/.doom.d/snippets/ is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Open org-agenda (org-agenda)
Recently opened files (recentf-open-files)
Open org-agenda (org-agenda)
Loading /home/swd/.emacs.d/.local/cache/recentf...done

org-mode restarted

org-mode restarted
org-gtd-agenda--prefix-format: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7>, 2
d ESC is undefined
line-move-finish: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7>, 2
eldoc error: (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7> 2)
line-move-finish: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7>, 2
eldoc error: (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7> 2)
line-move-finish: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7>, 2
eldoc error: (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7> 2)
line-move-finish: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7>, 2 [2 times]
Error in post-command-hook (evil-normal-post-command): (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7> 2)
Searched 0/1 files
Searched 1/1 files
Error in post-command-hook (evil-normal-post-command): (wrong-number-of-arguments #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_7> 2)
No other window to select
Debug on Error enabled globally
Entering debugger...
string-trim: Wrong type argument: stringp, 8.517193191416238
Entering debugger...
string-trim: Wrong type argument: stringp, 8.517193191416238
Entering debugger...
string-trim: Wrong type argument: stringp, 8.517193191416238
Entering debugger...
string-trim: Wrong type argument: stringp, 8.517193191416238
Entering debugger...
C-u 2 y
string-trim: Wrong type argument: stringp, 8.517193191416238
```

Here's how I'm setting things up in my config.el
```
(use-package! org-gtd
  :after org
  :demand t
  :custom
  (org-gtd-directory "~/gtd")
  (org-id-locations-file "~/.emacs.d/.org-id-locations")
  (org-edna-use-inheritance t)
  (org-gtd-organize-hooks '(org-gtd-set-area-of-focus org-set-tags-command))
  :config
  (org-edna-mode)
  :bind
  (("C-c d c" . org-gtd-capture)
   ("C-c d e" . org-gtd-engage)
   ("C-c d p" . org-gtd-process-inbox)
   :map org-gtd-clarify-map
   ("C-c c" . org-gtd-organize)))
```

**Comment by Trevoke** [comment] 2023-05-30 12:15
This is weird indeed. I ran the test suite on a 29 snapshot and it worked. 

I'll have to look at this at some point..  sounds like a problem I'll have to explore.

You may want to try removing the install files for org-gtd, once you've downgraded, and reinstalling org-gtd after. The byte compilation may have worked off of a changed elisp file between the emacs 29 pretests... Or it may be that this change https://github.com/Trevoke/org-gtd.el/pull/154 actually broke on emacs 29 somehow, despite the tests passing for me (I don't really know whether the snapshot I ran is before pretest2 or not).

**Comment by seelabs** [comment] 2023-05-30 13:02
I did remove the entire `.emacs.d` directory and reinstalled doom emacs from scratch when I downgraded emacs or recompiled without native compilation. One other change I made was enabling tree-sitter. I'm skeptical that's an issue, but I can recompile without that too and try again.

I'll also try to `git-bisect` if I can easily figure out how to install the package from a local directory instead of `(package! org-gtd)`.

**Comment by seelabs** [comment] 2023-05-30 13:19
I just recompiled without tree-sitter or native-compilation (on pretest2) and got similar error as before. The `Messages` buffer looks like this on this run:

```
Waiting for git... [2 times]
Warning: setting attribute ‘:background’ of face ‘font-lock-comment-face’: nil value is invalid, use ‘unspecified’ instead.
Doom loaded 235 packages across 43 modules in 1.143s
[yas] Check your `yas-snippet-dirs': /home/swd/.doom.d/snippets/ is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
C-c d is undefined [3 times]
Loading /home/swd/.emacs.d/.local/cache/recentf...done

org-mode restarted

org-mode restarted
string-trim-right: Wrong type argument: stringp, 0 [7 times]
string-trim-right: Wrong type argument: stringp, 49 [3 times]
Error in post-command-hook (evil-normal-post-command): (wrong-type-argument stringp 0)
string-trim-right: Wrong type argument: stringp, 49 [14 times]
```

**Comment by Trevoke** [comment] 2023-05-30 13:55
I'm not sure _why_ you're getting this particular message, but I'm curious about the `C-c d is undefined` message. I also notice you seem to be using `evil-mode`; maybe you're triggering an evil-mode command instead of an org-gtd command?

**Comment by seelabs** [comment] 2023-05-30 14:50
The `C-c d is undefined` message seems to be because it takes a little bit for the org-gtd to load (maybe 30 seconds or so). Before that's loaded properly the keybindings are undefined, after it loads I type `C-d d e` to run `org-gtd-engage` (which does bring up an agenda). So I don't think that message is related to the issue - that's just me typing the sequence a little to early.

I am running `evil-mode` (doom emacs, in fact), but it does correctly run the `org-gtd-engage` command and not some other command.

**Comment by dmgerman** [comment] 2023-05-30 22:05
Fix submitted #177

**Comment by Trevoke** [comment] 2023-05-31 01:01
This should be fixed with the latest org-gtd unstable release, thanks @dmgerman :) 

If this is still broken, @seelabs , please reopen this issue (or if you can't, put another message in there and I'll reopen it).

**Closed by Trevoke** 2023-05-31 01:01 UTC

**Comment by srijan** [comment] 2023-05-31 02:02
@Trevoke - I can confirm the fix works for me.

But, we should also look at why it was not caught by the test suite.

**Comment by dmgerman** [comment] 2023-05-31 02:27
> @Trevoke - I can confirm the fix works for me.
> 
> But, we should also look at why it was not caught by the test suite.

I think this is an untestable bug. This is basically the problem with languages that allow you to dynamically redefine a globally scoped language without a warning.
