### ISSUE TITLE
Merging inbox items into project when processing

### ISSUE THREAD

**Issue by cdlm** [Trevoke/org-gtd.el#108] opened 2023-02-15 09:02 UTC
I've just captured a few tasks in a row while brainstorming.

In the end, one of them is a project with most of the other ones as tasks, but the inbox processing workflow:
- prevents me from creating the project, since I'd have to type at least a couple tasks again,
- doesn't allow me to absorb the other items as tasks, because the buffer focuses on one item at a time.

Of course I can go and edit the inbox file, or I can think of capturing projects only and doing the brainstorming step later, during processing… but…

**Comment by cdlm** [comment] 2023-02-15 15:43
Heh… I'm not sure, I don't really have a fixed flow yet, I had a homebrewed GTD setup previously, then stopped using it for a while, until things started piling up again, and here am I trying `org-gtd`.

I'm pretty sure this case of capture first, structure afterwards will be a regular occurrence.
Maybe the easiest for me here is simply to widen the inbox during processing?

**Comment by Trevoke** [comment] 2023-03-11 02:18
I think I'm going to take care of this particular issue with 3.0 by adding a WIP property, which should help manage people getting interrupted while they do things 

See 
![image](https://user-images.githubusercontent.com/67913/224459856-68cd5667-c612-4b3e-90e2-033f56aac36f.png)

**Comment by Trevoke** [comment] 2023-05-15 21:47
With 3.0, the inbox view should be completely unobstructed during processing. Closing this, but if the problem isn't fixed, let me know / reopen!

**Closed by Trevoke** 2023-05-15 21:47 UTC
